### ISSUE TITLE
Getting a few errors when trying to create my cluster

### ISSUE THREAD

**Issue by steentottrup** [teamserverless/k8s-on-raspbian#17]
When trying to follow the manual steps, I get a few errors, I hope these can be addressed.

When running this:

    curl -sSL get.docker.com | sh && \
    sudo usermod pi -aG docker
    newgrp docker

I get this: `newgrp: group 'docker' does not exist`

Should it be??:

    curl -sSL get.docker.com | sh && \
    sudo usermod pi -aG docker \
    newgrp docker

Anyway, if I try running the lines above, I get this: `E: The repository 'https://download.docker.com/linux/raspbian 10 Release' does not have a Release file.`

And when moving on in the steps, I get the same error later on when running:

    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && \
      echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list && \
      sudo apt-get update -q && \
      sudo apt-get install -qy kubeadm

Any idea what this is? The is my first venture into kubernetes on Raspberry Pi, so it might just be me that's clueless here.

**Comment by DoGab** [comment]
@steentottrup What's the version of your raspbian release? I assume you are using raspbian buster. There currently is no available docker release for raspbian buster and that's why you get those errors.
Regarding the `newgrp docker`. If docker gets installed successfully via the script pulled with curl it will add a group `docker`. So there is no need to execute `newgrp docker`.

I've written a Tutorial how to install kubernetes version 1.15.0 on raspberry pi. You can follow the instructions [here](https://github.com/DoGab/k8s-raspi-cluster#workaround)

**Comment by steentottrup** [comment]
Oh sorry, I'm getting the latest Raspbian (Buster) Lite off their site, 2019-06-20-raspbian-buster-lite

Thank you!

**Comment by steentottrup** [comment]
Great tutorial, but you write that Raspbian Stretch is needed, and I can't seem to locate any version of Stretch, just Buster? (Can lite be used?)

**Comment by DoGab** [comment]
@steentottrup Lite is just a lightweight version of buster which contains less packages and no desktop ui. You can get old releases of raspbian [here](http://downloads.raspberrypi.org/raspbian/images/). Get the second latest release - `raspbian-2019-04-09/`.
Btw. i've updated the tutorial.

**Comment by steentottrup** [comment]
Thank you! I'm pretty much clueless at this, so your tutorial is getting a serious n00b review :)

**Comment by DoGab** [comment]
You're welcome! Sounds good, do not hesitate to contact me :) you can also open a new issue on my project so we can close this issue because it's actually solved.

**Comment by alexellis** [comment]
I would recommend still using stretch. There is a link in my comment in the main repo - follow through to the link about Buster and Docker being broken.

**Comment by alexellis** [comment]
@DoGab thanks for the assistance 👍
