### ISSUE TITLE
sudo kubeadm init always fails

### ISSUE THREAD

**Issue by daniel0m0baker** [teamserverless/k8s-on-raspbian#21]
When running `sudo kubeadm init --token-ttl=0 --pod-network-cidr=10.244.0.0/16` it always fatally errors out

## Expected Behaviour
This should complete the init

## Current Behaviour
`sudo kubeadm init --token-ttl=0 --pod-network-cidr=10.244.0.0/16`
This results in a timeout and fatal errors.
Applying the timeout API patch does not help at all:
`sudo sed -i 's/failureThreshold: 8/failureThreshold: 20/g' /etc/kubernetes/manifests/kube-apiserver.yaml && \
sudo sed -i 's/initialDelaySeconds: [0-9]\+/initialDelaySeconds: 360/' /etc/kubernetes/manifests/kube-apiserver.yaml`

## Context
I am setting up a new Raspberry Pi Master node.
This is repeatable, following this guide and always 100% results in this error.

## Your Environment
R-Pi 4
SanDisk Extreme Pro 128GB
All steps in the guide - no need to list that here.

* What version of Kubernetes are you using? `kubectl version`:
All steps in the guide - no need to list that here.

* Operating System and version (e.g. Linux, Windows, MacOS):
Raspian Lite

* What ARM or Raspberry Pi board are you using?
Raspberry Pi 4

**Comment by protheusfr** [comment]
+1

**Comment by alexellis** [comment]
Please seek out technical support from the kubeadm maintainers on the Kubernetes Slack, if you work out a resolution feel free to send a PR. http://slack.kubernetes.io

My recommendation is clearly stated in the README - use k3s which works flawlessly on RPi and uses far fewer resources.
