### ISSUE TITLE
Update swap disable instructions in GUIDE.md

### ISSUE THREAD

**Issue by petehalverson** [teamserverless/k8s-on-raspbian#22]
Follow @davidcollom's [comment in #16](https://github.com/teamserverless/k8s-on-raspbian/issues/16#issuecomment-506730599).
 
> swap would be enabled after each boot: `sudo systemctl disable dphys-swapfile` followed by a reboot, fixed this.

**Comment by DmitryZajcev** [comment]
+1

**Comment by alexellis** [comment]
Do you want to send a PR for this? Make sure you sign off the commit with `git commit -s`

See also k3s as the recommended K8s for ARMHF.

**Comment by alexellis** [comment]
I see a note here: `sudo systemctl disable dphys-swapfile`

But the documentation shows:

Turn off swap:

```sh
$ sudo dphys-swapfile swapoff && \
  sudo dphys-swapfile uninstall && \
  sudo update-rc.d dphys-swapfile remove
```

Are you saying that uninstalling and removing the unit file means it gets enabled on reboot?

**Comment by DmitryZajcev** [comment]
@alexellis, when I was following [the guide from medium](https://medium.com/nycdev/k8s-on-pi-9cc14843d43) I found that after raspberry reboot `sudo swapon --summary` command shows one swap enabled and I had to apply these swap disable instructions again.

**Comment by alexellis** [comment]
Wow he's completely ripped off my materials without crediting the source, this happens a lot and I don't think people understand copyright at all.

https://medium.com/nycdev/k8s-on-pi-9cc14843d43

I've added the command as suggested.
