### ISSUE TITLE
/proc/sys/net/bridge/bridge-nf-call-iptables not found 

### ISSUE THREAD

**Issue by yurilaaziz** [teamserverless/k8s-on-raspbian#5]
## Expected Behaviour
seems to be a missing configuration, Could you please add it in the tutorial as a comment or a note please.
## Current Behaviour
on raspbian, current version the /proc/sys/net/bridge/bridge-nf-call-iptables is not available  
## Possible Solution
`sudo modprobe br_netfilter
`
with persistence 
`echo "br_netfilter" >> /etc/modules`
## Steps to Reproduce (for bugs)

1. Install a fresh rasbian lite in a PI3 b +

## Your Environment
ARM PI 3 b+

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version of Kubernetes are you using? `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/arm"}

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

**Comment by alexellis** [comment]
Hi thanks for your interest in the project.

Just to say I didn't need this step and have tested all the instructions as given. 

Can you confirm the network driver being used?

Alex

**Comment by yurilaaziz** [comment]
As you suggest, flannel for arm.

**Comment by alexellis** [comment]
I'm going to close this issue, please feel free to send a PR to GUIDE.md
